### PR TITLE
Gas map shortcuts

### PR DESCRIPTION
**Pull request by witoldo7**

### CODE REVIEW

**Review by mattiasclaesson — COMMENTED** [review]
These are autogenerated from as2 files. I do not recommend to manually add to the dictionary.

**Comment by witoldo7** [comment]
have idea where can I find as2 file with description to 3 fuel bin ?

**Comment by MelvisR** [comment]
Already sorted, we are working on implementation.///Mackan Från: witoldo7Skickat: den 1 februari 2022 13:42Till: mattiasclaesson/TuningSuitesKopia: SubscribedÄmne: Re: [mattiasclaesson/TuningSuites] Gas map shortcuts & dictionary (PR #51) have idea where can I find as2 file with description to 3 fuel bin ?—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by mattiasclaesson** [comment]
I would like to keep your changes in the form 1 files. I will generate a new symboldictionary. Can you remove that file, please?

**Comment by witoldo7** [comment]
ok will update

**Pull request merged**
